name: Clean Deployment History
on:
    push:
        branches:
            - dev

jobs:
    cleanup:
        runs-on: ubuntu-latest
        permissions: write-all

        steps:
            - name: 🗑 Delete deployment
              uses: strumwolf/delete-deployment-environment@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  environment: dev
                  onlyRemoveDeployments: true
